-- MySQL Script generated by MySQL Workbench
-- Thu Jun 22 00:38:09 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema db_leafless
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_leafless
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_leafless` DEFAULT CHARACTER SET utf8mb3 ;
USE `db_leafless` ;

-- -----------------------------------------------------
-- Table `db_leafless`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_leafless`.`tb_usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome_completo` VARCHAR(255) NOT NULL,
  `nome_apresentacao` VARCHAR(45) NULL DEFAULT NULL,
  `data_cadastro` DATE NOT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `cpf` VARCHAR(11) NULL DEFAULT NULL,
  `email` VARCHAR(45) NULL DEFAULT NULL,
  `empresa` VARCHAR(25) NULL DEFAULT NULL,
  `cargo` VARCHAR(45) NULL DEFAULT NULL,
  `telefone_comercial` VARCHAR(14) NULL DEFAULT NULL,
  `username` VARCHAR(15) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_leafless`.`tb_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_leafless`.`tb_documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(255) NOT NULL,
  `data_inclusao` DATETIME NOT NULL,
  `caminho` VARCHAR(255) NOT NULL,
  `extensao` VARCHAR(7) NOT NULL,
  `versao` VARCHAR(3) NOT NULL,
  `temporalidade` INT NULL DEFAULT NULL,
  `nome_autor` VARCHAR(255) NULL DEFAULT NULL,
  `tb_usuarios_id_autor` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_tb_documentos_tb_usuarios1_idx` (`tb_usuarios_id_autor` ASC) VISIBLE,
  CONSTRAINT `fk_tb_documentos_tb_usuarios1`
    FOREIGN KEY (`tb_usuarios_id_autor`)
    REFERENCES `db_leafless`.`tb_usuarios` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 28
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_leafless`.`tb_grupos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_leafless`.`tb_grupos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 29
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_leafless`.`tb_grupos_mtm_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_leafless`.`tb_grupos_mtm_documentos` (
  `tb_grupos_id` INT NOT NULL,
  `tb_documentos_id` INT NOT NULL,
  PRIMARY KEY (`tb_grupos_id`, `tb_documentos_id`),
  INDEX `fk_tb_grupos_has_tb_documentos_tb_documentos1_idx` (`tb_documentos_id` ASC) VISIBLE,
  INDEX `fk_tb_grupos_has_tb_documentos_tb_grupos1_idx` (`tb_grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_grupos_has_tb_documentos_tb_documentos1`
    FOREIGN KEY (`tb_documentos_id`)
    REFERENCES `db_leafless`.`tb_documentos` (`id`),
  CONSTRAINT `fk_tb_grupos_has_tb_documentos_tb_grupos1`
    FOREIGN KEY (`tb_grupos_id`)
    REFERENCES `db_leafless`.`tb_grupos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `db_leafless`.`tb_grupos_mtm_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_leafless`.`tb_grupos_mtm_usuarios` (
  `tb_grupos_id` INT NOT NULL,
  `tb_usuarios_id` INT NOT NULL,
  PRIMARY KEY (`tb_grupos_id`, `tb_usuarios_id`),
  INDEX `fk_tb_grupos_has_tb_usuarios_tb_usuarios1_idx` (`tb_usuarios_id` ASC) VISIBLE,
  INDEX `fk_tb_grupos_has_tb_usuarios_tb_grupos1_idx` (`tb_grupos_id` ASC) VISIBLE,
  CONSTRAINT `fk_tb_grupos_has_tb_usuarios_tb_grupos1`
    FOREIGN KEY (`tb_grupos_id`)
    REFERENCES `db_leafless`.`tb_grupos` (`id`),
  CONSTRAINT `fk_tb_grupos_has_tb_usuarios_tb_usuarios1`
    FOREIGN KEY (`tb_usuarios_id`)
    REFERENCES `db_leafless`.`tb_usuarios` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
