/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package newTelas;

import db.Conexao;
import telas.Login;

import java.awt.*;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author wellersonelucas
 */
public class VerDocumento extends javax.swing.JFrame {
        
    
    boolean verAcao = false;
    /**
     * Creates new form ExcluirArquivo
     */
    public VerDocumento() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPesquisar = new javax.swing.JPanel();
        jTextParaPesquisar = new javax.swing.JTextField();
        btPesquisar = new javax.swing.JToggleButton();
        jTexcluirarquivo = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        labelCadastro = new java.awt.Label();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelPesquisar.setBackground(new java.awt.Color(19, 30, 53));

        jTextParaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextParaPesquisarActionPerformed(evt);
            }
        });

        btPesquisar.setBackground(new java.awt.Color(58, 93, 174));
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        jTexcluirarquivo.setBackground(new java.awt.Color(167, 36, 36));
        jTexcluirarquivo.setText("Excluir arquivo");
        jTexcluirarquivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexcluirarquivoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(229, 229, 229));
        jLabel1.setText("Título do documento:");

        labelCadastro.setAlignment(java.awt.Label.CENTER);
        labelCadastro.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelCadastro.setForeground(new java.awt.Color(229, 229, 229));
        labelCadastro.setText("Visualizar Documento");

        javax.swing.GroupLayout jPanelPesquisarLayout = new javax.swing.GroupLayout(jPanelPesquisar);
        jPanelPesquisar.setLayout(jPanelPesquisarLayout);
        jPanelPesquisarLayout.setHorizontalGroup(
            jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jTextParaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btPesquisar))
                .addContainerGap(108, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPesquisarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTexcluirarquivo)
                .addGap(60, 60, 60))
        );
        jPanelPesquisarLayout.setVerticalGroup(
            jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPesquisarLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(labelCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addGroup(jPanelPesquisarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextParaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(btPesquisar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                .addComponent(jTexcluirarquivo)
                .addGap(60, 60, 60))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextParaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextParaPesquisarActionPerformed
       
    }//GEN-LAST:event_jTextParaPesquisarActionPerformed

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
     
        {


        try {
            Connection con = Conexao.fazConexao();
            String sql = "SELECT * FROM tb_documentos WHERE nome_autor = ? AND titulo = ?";
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, Login.naofazer);
            ps.setString(2, jTextParaPesquisar.getText());

            ResultSet rs = ps.executeQuery();

            //verAcao = rs.next();
            if (rs.next()) {
                // Caso o usuário exista e as credenciais estejam corretas
                JOptionPane.showMessageDialog(null, "deu certo");
                sql = "SELECT caminho FROM tb_documentos WHERE nome_autor =? AND titulo = ?";
                ps = con.prepareStatement(sql);
                ps.setString(1, Login.naofazer);
                ps.setString(2, jTextParaPesquisar.getText());


                rs = ps.executeQuery();
                if (rs.next()) {
                    String caminho = rs.getString("caminho");
                    // Faça o que desejar com a variável caminho
                    System.out.println("Caminho do arquivo: " + caminho);
                    verAcao = true;

                    File arquivo = new File(caminho);

                    if (arquivo.exists()) {
                        try {
                            Desktop.getDesktop().open(arquivo);
                        } catch (IOException e) {
                            e.printStackTrace();
                        }
                    } else {
                        System.out.println("Arquivo PDF não encontrado!");
                    }




                } else {
                    System.out.println("Nenhum resultado encontrado.");
                }




            } else {
                // Caso o usuário não exista ou as credenciais estejam incorretas
                JOptionPane.showMessageDialog(null, "Arquivo não encontrado");
            }

            con.close();
        } catch (SQLException e) {
            e.printStackTrace();
        }



    }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private void jTexcluirarquivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexcluirarquivoActionPerformed
       
        int opcao = JOptionPane.showOptionDialog(null, "Deseja excluir o arquivo?", "Confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, null, null);

        if (opcao == JOptionPane.YES_OPTION) {
            if(verAcao){
                try{Connection con = Conexao.fazConexao();
                    String sql = "DELETE FROM tb_documentos WHERE nome_autor = ? and titulo =? ";
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, Login.naofazer);
                    ps.setString(2, jTextParaPesquisar.getText());

                    ps.executeUpdate();

                    JOptionPane.showMessageDialog(null, "Arquivo excluído com sucesso!");
                }
                catch (SQLException e) {
                    e.printStackTrace();
                }
            }else{
                JOptionPane.showMessageDialog(null,"É necessário visualizar o arquivo para excluir");
            }



        } else {

        }

        if(verAcao){
            try{Connection con = Conexao.fazConexao();
                String sql = "DELETE FROM tb_documentos WHERE nome_autor = ? and titulo =? ";
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, Login.naofazer);
                ps.setString(2, jTextParaPesquisar.getText());

                ps.executeUpdate();

                JOptionPane.showMessageDialog(null, "Arquivo excluído com sucesso!");
            }
            catch (SQLException e) {
                e.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(null,"É necessário visualizar o arquivo para excluir");
        }
    
    }//GEN-LAST:event_jTexcluirarquivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VerDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VerDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VerDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VerDocumento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VerDocumento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btPesquisar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanelPesquisar;
    private javax.swing.JToggleButton jTexcluirarquivo;
    private javax.swing.JTextField jTextParaPesquisar;
    private java.awt.Label labelCadastro;
    // End of variables declaration//GEN-END:variables
}
